# kubectl apply -f angelina-napaico-26-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: angelina-napaico-26-secret
  namespace: angelina-napaico-26-namespace
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9hbmdlbGluYW5hcGFpY29fZGJfdXNlcjphbmdlMTIzNDU2NzhAY2x1c3RlcjAuaGlpemQxYS5tb25nb2RiLm5ldC9pYV9kYj9hcHBOYW1lPUNsdXN0ZXIw   # en Base64
  DATABASE_USERNAME: aWFfZGI=   # en Base64
  DATABASE_PASSWORD: YW5nZTEyMzQ1Njc4   # en Base64
  RAPIDAPI_URL: aHR0cHM6Ly9kZWVwLXRyYW5zbGF0ZTEucC5yYXBpZGFwaS5jb20vbGFuZ3VhZ2UvdHJhbnNsYXRlL3Yy   # en Base64
  RAPIDAPI_HOST: ZGVlcC10cmFuc2xhdGUxLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_APIKEY: Yzc2NzBkYjIyOG1zaDRjMGFlZTVlOWEyY2UyMnAxNGJmOTVqc25kZmQwNjUxODJlNDM=   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode
